/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/consumption/index" |
       "/pages/customDemo/index" |
       "/pages/echartsDemo/index" |
       "/pages/hairstylist/list" |
       "/pages/i18nDemo/index" |
       "/pages/layoutDemo/index" |
       "/pages/member/detail" |
       "/pages/member/edit" |
       "/pages/member/list" |
       "/pages/piniaDemo/index" |
       "/pages/queryDemo/loginDemo" |
       "/pages/queryDemo/queryTestDemo" |
       "/pages/queryDemo/useRequestDemo" |
       "/pages/queryDemo/zPagingDemo" |
       "/pages/recharge/index" |
       "/pages/report/index" |
       "/pages/routerDemo/index" |
       "/pages/routerDemo/login" |
       "/pages/routerDemo/page1" |
       "/pages/routerDemo/page2" |
       "/pages/routerDemo/page3" |
       "/pages/serviceType/list" |
       "/pages/settings/index" |
       "/pages/unocssDemo/index" |
       "/pages/wotUiDemo/index" |
       "/pages-sub/subDemo/index" |
       "/pages-sub/testDemo/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/member/list" | "/pages/recharge/index" | "/pages/consumption/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
